**Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow**

How to compute the eigenvalues and right eigenvectors of a given square array using NumPy library.

In [9]:
import tensorflow as tf

m = tf.constant([[1, 2], [2, 3]], dtype=tf.float32)
eigenvalues, eigenvectors = tf.linalg.eig(m)
print(eigenvalues.numpy())
print(eigenvectors.numpy())

import numpy as np
m = np.array([[1, 2],
			[2, 3]])
print("Printing the Original square array:\n",m)
w, v = np.linalg.eig(m)
print("Printing the Eigen values of the given square array:\n",w)
print("Printing Right Eigen Vectors of the given square array:\n",v)

import numpy as np
m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

print("Printing the Original square array:\n",m)
w, v = np.linalg.eig(m)

print("Eigen values of the given square array:\n",w)
print("Eigenvectors of the given square array:\n",v)

!pip install tensorflow
!pip install tensorflow[and-cuda]

import tensorflow as tf
e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")
print("Matrix A: \n{}\n\n".format(e_matrix_A))

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")
print("Matrix A: \n{}\n\n".format(e_matrix_A))

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

[-0.23606804+0.j  4.2360687 +0.j]
[[-0.85065085+0.j -0.52573115+0.j]
 [ 0.52573115+0.j -0.85065085+0.j]]
Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right Eigen Vectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]
Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01  1.01486082e-16]
Eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Matrix A: 
[[5.9354944 9.729846 ]
 [7.3089914 7.9980493]]


Eigen Vectors: 
[[-0.75488853 -0.6558532 ]
 [ 0.6558532  -0.75488853]] 

Eigen Values: 
[-0.41461667 14.348162  ]

Matrix A: 
[[3.2782717 6.0768814 9.044252 ]
 [3.9456491 3.2467813 8.0695305]
 [5.468708  6.206593  5.816544 ]]


Eigen Vectors: 
[[ 0.23254536 -0.83144706  0.50459737]
 [ 0.67080504  0.5127833   0.53579295]
 [-0.7042323   0.21389031  0.6769844 ]] 

Eigen Values: 
[-1.9012728  -0.56198007 14.804855  ]




[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip
